version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "80:8087"
    volumes:
      - .:/app
    links:
      - mongodb:mongo
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"